import type { InsertProduct } from "@shared/schema";

// DealControl Asset Library - 47 Assets + Bundles
// VERITAS-1 Λ Elite Tier compliant
export const dealControlProducts: InsertProduct[] = [
  // ============================================
  // WAVE 1: Revenue Proof (Assets 1-10) - Featured
  // ============================================
  {
    title: "Texas Executor Property Sale Checklist",
    description: "Step-by-step checklist for executors selling estate property in Texas. Covers probate requirements, title clearance, disclosure obligations, and timeline management.",
    category: "Estate & Probate",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/texas_executor_checklist.png",
    price: 12900,
    isFeatured: 1,
    assetType: "checklist",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Probate delays, title defects, disclosure violations, heir disputes",
  },
  {
    title: "Earnest Money Dispute Prevention SOP",
    description: "Standard operating procedure for handling earnest money to prevent disputes. Includes escrow protocols, release conditions, and documentation requirements.",
    category: "Transaction Management",
    format: "SOP",
    imageUrl: "/attached_assets/generated_images/earnest_money_dispute_sop.png",
    price: 12900,
    isFeatured: 1,
    assetType: "sop",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Earnest money disputes, escrow violations, buyer/seller conflicts",
  },
  {
    title: "First-Time Landlord Mistake Prevention SOP",
    description: "Comprehensive guide for new landlords covering tenant screening, lease execution, security deposits, maintenance protocols, and eviction procedures.",
    category: "Landlord Operations",
    format: "SOP",
    imageUrl: "/attached_assets/generated_images/first-time_landlord_sop.png",
    price: 12900,
    isFeatured: 1,
    assetType: "sop",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Fair housing violations, security deposit mishandling, lease gaps, eviction errors",
  },
  {
    title: "Heir Interference Prevention SOP",
    description: "Protocols for managing multiple heirs during estate sales. Covers communication, decision authority, conflict resolution, and documentation.",
    category: "Estate & Probate",
    format: "SOP",
    imageUrl: "/attached_assets/generated_images/heir_interference_prevention_sop.png",
    price: 12900,
    isFeatured: 1,
    assetType: "sop",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Heir conflicts, unauthorized property access, sale delays, legal disputes",
  },
  {
    title: "Mortgage Loan Fallout Prevention Checklist",
    description: "Pre-qualification and monitoring checklist to prevent financing failures. Covers credit requirements, documentation, and red flags to watch.",
    category: "Transaction Management",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/mortgage_fallout_prevention.png",
    price: 12900,
    isFeatured: 1,
    assetType: "checklist",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Financing denial, closing delays, deal collapse, commission loss",
  },
  {
    title: "Buyer Credit Readiness Pre-Screen SOP",
    description: "Systematic process for evaluating buyer financial readiness before showing properties. Includes credit review, income verification, and debt-to-income analysis.",
    category: "Transaction Management",
    format: "SOP",
    imageUrl: "/attached_assets/generated_images/buyer_credit_pre-screen_sop.png",
    price: 12900,
    isFeatured: 1,
    assetType: "sop",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Unqualified buyers, wasted showings, financing failures",
  },
  {
    title: "Inspection Objection Negotiation Script",
    description: "Word-for-word scripts for negotiating inspection objections. Covers repair requests, credits, and walk-away scenarios.",
    category: "Negotiation",
    format: "Script",
    imageUrl: "/attached_assets/generated_images/inspection_negotiation_script.png",
    price: 12900,
    isFeatured: 1,
    assetType: "script",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Deal collapse from inspection issues, over-negotiation, liability exposure",
  },
  {
    title: "Appraisal Gap Strategy Guide",
    description: "Decision framework for handling appraisal gaps. Includes negotiation strategies, gap financing options, and deal restructuring approaches.",
    category: "Transaction Management",
    format: "Guide",
    imageUrl: "/attached_assets/generated_images/appraisal_gap_strategy_guide.png",
    price: 12900,
    isFeatured: 1,
    assetType: "guide",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Appraisal shortfalls, deal collapse, renegotiation failures",
  },
  {
    title: "Financing Fallout Response Playbook",
    description: "Emergency response protocols when financing falls through. Covers backup options, timeline extensions, and deal salvage strategies.",
    category: "Transaction Management",
    format: "Playbook",
    imageUrl: "/attached_assets/generated_images/financing_fallout_playbook.png",
    price: 12900,
    isFeatured: 1,
    assetType: "playbook",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Financing denial, closing deadline failures, backup plan gaps",
  },
  {
    title: "Divorce-Related Property Sale Playbook",
    description: "Comprehensive playbook for handling property sales during divorce proceedings. Covers dual-client protocols, court requirements, and conflict management.",
    category: "Specialized Sales",
    format: "Playbook",
    imageUrl: "/attached_assets/generated_images/divorce_property_sale_playbook.png",
    price: 14900,
    isFeatured: 1,
    assetType: "playbook",
    priceSolo: 14900,
    pricePro: 24900,
    priceOffice: 79900,
    risksAddressed: "Dual-representation conflicts, court compliance, proceeds distribution disputes",
  },

  // ============================================
  // WAVE 2: Core Ops (Assets 11-20)
  // ============================================
  {
    title: "Multiple Offer Handling Checklist",
    description: "Systematic approach to managing multiple offers. Covers presentation order, disclosure requirements, counter-offer strategies, and documentation.",
    category: "Transaction Management",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/multiple_offer_handling_checklist.png",
    price: 12900,
    isFeatured: 0,
    assetType: "checklist",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Disclosure violations, bid manipulation claims, seller liability",
  },
  {
    title: "Backup Offer Management SOP",
    description: "Protocols for positioning and managing backup offers. Includes activation procedures, earnest money handling, and timeline management.",
    category: "Transaction Management",
    format: "SOP",
    imageUrl: "/attached_assets/generated_images/backup_offer_management_sop.png",
    price: 12900,
    isFeatured: 0,
    assetType: "sop",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Backup offer disputes, contract priority conflicts, earnest money confusion",
  },
  {
    title: "Price Reduction Decision Framework",
    description: "Data-driven framework for recommending and executing price reductions. Includes market analysis triggers, client communication scripts, and timing strategies.",
    category: "Listing Management",
    format: "Framework",
    imageUrl: "/attached_assets/generated_images/price_reduction_framework.png",
    price: 12900,
    isFeatured: 0,
    assetType: "framework",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Stale listings, seller resistance, overpricing consequences",
  },
  {
    title: "Days-on-Market Reset Playbook",
    description: "Strategies for resetting DOM and relaunching stale listings. Covers MLS protocols, marketing refresh, and repositioning tactics.",
    category: "Listing Management",
    format: "Playbook",
    imageUrl: "/attached_assets/generated_images/days-on-market_reset_playbook.png",
    price: 12900,
    isFeatured: 0,
    assetType: "playbook",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "DOM stigma, stale inventory, seller frustration",
  },
  {
    title: "New Client Intake SOP - Buyer",
    description: "Complete onboarding process for buyer clients. Covers qualification, needs assessment, agency disclosure, and expectation setting.",
    category: "Client Management",
    format: "SOP",
    imageUrl: "/attached_assets/generated_images/new_client_intake_buyer_sop.png",
    price: 12900,
    isFeatured: 0,
    assetType: "sop",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Agency violations, unqualified clients, misaligned expectations",
  },
  {
    title: "New Client Intake SOP - Seller",
    description: "Complete onboarding process for seller clients. Covers listing presentation, pricing strategy, disclosure requirements, and marketing plan.",
    category: "Client Management",
    format: "SOP",
    imageUrl: "/attached_assets/generated_images/new_client_intake_seller_sop.png",
    price: 12900,
    isFeatured: 0,
    assetType: "sop",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Disclosure gaps, pricing disputes, marketing commitment issues",
  },
  {
    title: "Seller Readiness Checklist",
    description: "Pre-listing preparation checklist for sellers. Covers repairs, staging, documentation, and property access protocols.",
    category: "Listing Management",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/seller_readiness_checklist.png",
    price: 9900,
    isFeatured: 0,
    assetType: "checklist",
    priceSolo: 9900,
    pricePro: 17900,
    priceOffice: 49900,
    risksAddressed: "Unprepared listings, showing access issues, disclosure gaps",
  },
  {
    title: "Transaction Timeline Communication Template",
    description: "Standardized timeline templates for keeping all parties informed. Covers milestone notifications, deadline reminders, and status updates.",
    category: "Transaction Management",
    format: "Template",
    imageUrl: "/attached_assets/generated_images/transaction_timeline_template.png",
    price: 9900,
    isFeatured: 0,
    assetType: "template",
    priceSolo: 9900,
    pricePro: 17900,
    priceOffice: 49900,
    risksAddressed: "Missed deadlines, communication gaps, client confusion",
  },
  {
    title: "Client Expectation Setting Script",
    description: "Scripts for setting realistic expectations with buyers and sellers. Covers market conditions, timelines, pricing, and process education.",
    category: "Client Management",
    format: "Script",
    imageUrl: "/attached_assets/generated_images/client_expectation_script.png",
    price: 12900,
    isFeatured: 0,
    assetType: "script",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Unrealistic expectations, client disappointment, relationship damage",
  },
  {
    title: "Seller Expectation Alignment Script",
    description: "Specific scripts for aligning seller expectations on pricing, timeline, and market conditions. Includes objection handling and reframing techniques.",
    category: "Client Management",
    format: "Script",
    imageUrl: "/attached_assets/generated_images/seller_expectation_script.png",
    price: 12900,
    isFeatured: 0,
    assetType: "script",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Overpricing resistance, timeline disputes, market denial",
  },

  // ============================================
  // WAVE 3: Landlord Risk (Assets 21-27)
  // ============================================
  {
    title: "Tenant Screening Compliance Checklist",
    description: "Fair housing compliant tenant screening process. Covers application review, background checks, income verification, and documentation.",
    category: "Landlord Operations",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/tenant_screening_compliance.png",
    price: 12900,
    isFeatured: 0,
    assetType: "checklist",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Fair housing violations, discrimination claims, bad tenant selection",
  },
  {
    title: "Security Deposit Handling SOP",
    description: "State-compliant protocols for collecting, holding, and returning security deposits. Includes documentation templates and timeline requirements.",
    category: "Landlord Operations",
    format: "SOP",
    imageUrl: "/attached_assets/generated_images/security_deposit_handling_sop.png",
    price: 12900,
    isFeatured: 0,
    assetType: "sop",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Deposit disputes, statutory violations, penalty exposure",
  },
  {
    title: "Lease Violation Response Checklist",
    description: "Step-by-step response protocols for lease violations. Covers notice requirements, documentation, cure periods, and escalation procedures.",
    category: "Landlord Operations",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/lease_violation_checklist.png",
    price: 12900,
    isFeatured: 0,
    assetType: "checklist",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Improper notice, eviction dismissal, retaliation claims",
  },
  {
    title: "Contractor Scope Control Checklist",
    description: "Protocols for defining, documenting, and managing contractor work. Covers scope definition, change orders, payment schedules, and liability.",
    category: "Property Management",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/contractor_scope_control_checklist.png",
    price: 12900,
    isFeatured: 0,
    assetType: "checklist",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    risksAddressed: "Scope creep, cost overruns, lien exposure, quality disputes",
  },
  {
    title: "FSBO Rescue Agent Playbook",
    description: "Strategies for converting expired FSBOs to listings. Covers approach timing, value proposition scripts, and objection handling.",
    category: "Lead Conversion",
    format: "Playbook",
    imageUrl: "/attached_assets/generated_images/fsbo_rescue_agent_playbook.png",
    price: 14900,
    isFeatured: 0,
    assetType: "playbook",
    priceSolo: 14900,
    pricePro: 24900,
    priceOffice: 79900,
    risksAddressed: "Lost listing opportunities, poor conversion rates, competitive loss",
  },
  {
    title: "Investor Kill-Criteria Checklist",
    description: "Due diligence checklist for investment property evaluation. Covers deal-breakers, red flags, and minimum requirements for different strategies.",
    category: "Investment",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/investor_kill-criteria_checklist.png",
    price: 14900,
    isFeatured: 0,
    assetType: "checklist",
    priceSolo: 14900,
    pricePro: 24900,
    priceOffice: 79900,
    risksAddressed: "Bad investment decisions, hidden problems, ROI miscalculation",
  },
  {
    title: "Mortgage Denial Recovery Playbook",
    description: "Emergency response guide when buyers are denied financing. Covers alternative lenders, loan restructuring, and deal preservation strategies.",
    category: "Transaction Management",
    format: "Playbook",
    imageUrl: "/attached_assets/generated_images/mortgage_denial_recovery_playbook.png",
    price: 14900,
    isFeatured: 0,
    assetType: "playbook",
    priceSolo: 14900,
    pricePro: 24900,
    priceOffice: 79900,
    risksAddressed: "Lost deals, client abandonment, commission loss",
  },

  // ============================================
  // WAVE 4: Estate/Probate Authority (Assets 28-33)
  // ============================================
  {
    title: "Out-of-State Executor SOP",
    description: "Protocols for supporting executors managing Texas property from out of state. Covers remote management, local representation, and communication systems.",
    category: "Estate & Probate",
    format: "SOP",
    imageUrl: "/attached_assets/generated_images/out-of-state_executor_sop.png",
    price: 14900,
    isFeatured: 0,
    assetType: "sop",
    priceSolo: 14900,
    pricePro: 24900,
    priceOffice: 79900,
    risksAddressed: "Remote management gaps, local compliance issues, communication failures",
  },

  // ============================================
  // BUNDLES - Premium Packages
  // ============================================
  {
    title: "Transaction Risk Control Kit - Solo",
    description: "Essential bundle for individual agents. Includes: Earnest Money SOP, Financing Fallout Playbook, Inspection Negotiation Script, Appraisal Gap Guide, and Transaction Timeline Template.",
    category: "Bundles",
    format: "Bundle",
    imageUrl: "/attached_assets/generated_images/transaction_risk_control_kit_solo.png",
    price: 49900,
    isFeatured: 1,
    assetType: "bundle",
    tier: "solo",
    priceSolo: 49900,
    pricePro: 89900,
    priceOffice: 249900,
    risksAddressed: "Transaction failures, financing issues, negotiation gaps, timeline mismanagement",
  },
  {
    title: "Transaction Risk Control Kit - Pro",
    description: "Team bundle with expanded rights. All Solo assets plus team training materials and implementation guides. Licensed for up to 10 users.",
    category: "Bundles",
    format: "Bundle",
    imageUrl: "/attached_assets/generated_images/transaction_risk_control_kit_pro.png",
    price: 89900,
    isFeatured: 0,
    assetType: "bundle",
    tier: "pro",
    priceSolo: 49900,
    pricePro: 89900,
    priceOffice: 249900,
    risksAddressed: "Transaction failures, financing issues, negotiation gaps, timeline mismanagement",
  },
  {
    title: "Transaction Risk Control Kit - Office",
    description: "Brokerage-wide license. All Pro assets plus customization rights, white-label options, and unlimited user deployment.",
    category: "Bundles",
    format: "Bundle",
    imageUrl: "/attached_assets/generated_images/transaction_risk_control_office_license.png",
    price: 249900,
    isFeatured: 0,
    assetType: "bundle",
    tier: "office",
    priceSolo: 49900,
    pricePro: 89900,
    priceOffice: 249900,
    risksAddressed: "Transaction failures, financing issues, negotiation gaps, timeline mismanagement",
  },
  {
    title: "Estate Sale Control Pack - Solo",
    description: "Complete estate sale toolkit for individual agents. Includes: Texas Executor Checklist, Heir Interference SOP, Out-of-State Executor SOP, and estate-specific scripts.",
    category: "Bundles",
    format: "Bundle",
    imageUrl: "/attached_assets/generated_images/estate_sale_control_pack_solo.png",
    price: 59900,
    isFeatured: 0,
    assetType: "bundle",
    tier: "solo",
    priceSolo: 59900,
    pricePro: 99900,
    priceOffice: 299900,
    risksAddressed: "Probate complications, heir conflicts, executor liability, compliance gaps",
  },
  {
    title: "Estate Sale Control Pack - Pro",
    description: "Team bundle for estate specialists. All Solo assets plus team training and expanded implementation guides. Licensed for up to 10 users.",
    category: "Bundles",
    format: "Bundle",
    imageUrl: "/attached_assets/generated_images/estate_sale_control_pack_pro.png",
    price: 99900,
    isFeatured: 0,
    assetType: "bundle",
    tier: "pro",
    priceSolo: 59900,
    pricePro: 99900,
    priceOffice: 299900,
    risksAddressed: "Probate complications, heir conflicts, executor liability, compliance gaps",
  },
  {
    title: "Estate Sale Control Pack - Office",
    description: "Brokerage license for estate sale specialization. All Pro assets plus customization, white-label, and unlimited deployment.",
    category: "Bundles",
    format: "Bundle",
    imageUrl: "/attached_assets/generated_images/estate_sale_control_pack_office.png",
    price: 299900,
    isFeatured: 0,
    assetType: "bundle",
    tier: "office",
    priceSolo: 59900,
    pricePro: 99900,
    priceOffice: 299900,
    risksAddressed: "Probate complications, heir conflicts, executor liability, compliance gaps",
  },
  {
    title: "Landlord Liability Shield - Solo",
    description: "Risk management bundle for landlords. Includes: First-Time Landlord SOP, Tenant Screening Checklist, Security Deposit SOP, and Lease Violation Checklist.",
    category: "Bundles",
    format: "Bundle",
    imageUrl: "/attached_assets/generated_images/landlord_liability_shield_solo.png",
    price: 49900,
    isFeatured: 0,
    assetType: "bundle",
    tier: "solo",
    priceSolo: 49900,
    pricePro: 89900,
    priceOffice: 249900,
    risksAddressed: "Fair housing violations, security deposit claims, eviction errors, lease gaps",
  },
  {
    title: "Landlord Liability Shield - Pro",
    description: "Property manager bundle. All Solo assets plus portfolio management tools and team training. Licensed for up to 10 users.",
    category: "Bundles",
    format: "Bundle",
    imageUrl: "/attached_assets/generated_images/landlord_liability_shield_pro.png",
    price: 89900,
    isFeatured: 0,
    assetType: "bundle",
    tier: "pro",
    priceSolo: 49900,
    pricePro: 89900,
    priceOffice: 249900,
    risksAddressed: "Fair housing violations, security deposit claims, eviction errors, lease gaps",
  },
  {
    title: "Landlord Liability Shield - Office",
    description: "Property management company license. All Pro assets plus customization, white-label, and unlimited deployment.",
    category: "Bundles",
    format: "Bundle",
    imageUrl: "/attached_assets/generated_images/landlord_liability_shield_office.png",
    price: 249900,
    isFeatured: 0,
    assetType: "bundle",
    tier: "office",
    priceSolo: 49900,
    pricePro: 89900,
    priceOffice: 249900,
    risksAddressed: "Fair housing violations, security deposit claims, eviction errors, lease gaps",
  },

  // ============================================
  // M.I.F.G.E. - Most Incredible Free Gift Ever
  // HIDDEN - Not shown in library, only via funnel
  // ============================================
  {
    title: "DealControl Starter System",
    description: "The complete done-for-you system to protect every transaction from day one. Includes 12 battle-tested SOPs, checklists, and scripts worth $1,497 - yours FREE. Contains: Transaction Risk Control Kit (Solo), Earnest Money Dispute Prevention SOP, Mortgage Fallout Prevention Checklist, Inspection Negotiation Script, Appraisal Gap Strategy Guide, Financing Fallout Playbook, Client Expectation Setting Script, Buyer Credit Pre-Screen SOP, Transaction Timeline Template, Quick-Start Implementation Guide, and Video Training Overview.",
    category: "MIFGE",
    format: "System",
    imageUrl: "/attached_assets/generated_images/transaction_risk_control_kit_solo.png",
    price: 0,
    isFeatured: 0,
    assetType: "mifge",
    tier: "starter",
    priceSolo: 0,
    pricePro: 0,
    priceOffice: 0,
    risksAddressed: "Transaction failures, financing issues, client disputes, deal collapse, commission loss, liability exposure",
  },

  // ============================================
  // OTO - One Time Offer (Best Thing)
  // HIDDEN - Only shown after first purchase
  // ============================================
  {
    title: "DealControl Ultimate Mastery System",
    description: "The COMPLETE DealControl arsenal - every SOP, checklist, script, playbook, and bundle we've ever created, PLUS exclusive bonuses you can't get anywhere else. Includes: ALL 37 individual assets (Office-level licenses), ALL 9 premium bundles, Lifetime updates & new releases, Priority implementation support, Private Mastermind Community access, Monthly live Q&A calls, Custom white-label rights, and Founding Member status. This is the ONE TIME you'll ever see this offer at this price. Total value: $8,994 - Today only: $1,997",
    category: "OTO",
    format: "Ultimate",
    imageUrl: "/attached_assets/generated_images/transaction_risk_control_office_license.png",
    price: 199700,
    isFeatured: 0,
    assetType: "oto",
    tier: "ultimate",
    priceSolo: 199700,
    pricePro: 199700,
    priceOffice: 199700,
    risksAddressed: "Every transaction risk, liability exposure, compliance gaps, team training, scalability limitations",
  },
];

