import ws from "ws";
import { DatabaseStorage } from "./storage.js";
import type { InsertProduct, InsertFunnel, InsertFunnelStep, InsertOrderBump } from "@shared/schema";

if (!globalThis.WebSocket) {
  globalThis.WebSocket = ws as any;
}

const storage = new DatabaseStorage();

// Texas Real Estate Products - Tier 1: Immediate Pain / Legal or Money Risk (10 products)
const texasRealEstateTier1: InsertProduct[] = [
  {
    title: "Texas Executor Property Sale Checklist",
    description: "Complete step-by-step checklist for selling estate property in Texas. Covers court requirements, heir notifications, title clearance, and timeline management. Prevents costly legal mistakes and delays.",
    category: "Real Estate",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/texas_executor_checklist.png",
    price: 12900,
    isFeatured: 1,
    assetType: "checklist",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This checklist helps licensed Texas real estate agents navigate probate property sales with court-required documentation, heir notification procedures, and title clearance protocols.",
    useConditions: "Use when: Representing executor in estate property sale, probate court involvement, multiple heirs with ownership interest. Not applicable when: Standard residential sale without estate involvement, property already transferred to single heir.",
    risksAddressed: "Addresses: Probate court filing errors, heir notification failures, title cloud issues, timeline violations, improper documentation leading to sale delays or litigation.",
    coreContent: "17-step probate sale checklist covering Letters Testamentary verification, heir notification requirements, court approval timelines, title examination protocols, and closing coordination procedures.",
    failurePoints: "Common failure points: Missing heir signatures causing title delays, incorrect court filing procedures, failure to obtain proper authorization before listing.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Store heir notification receipts and court approval documentation indefinitely.",
    judgmentBoundary: "Requires agent judgment when: Heirs dispute sale terms, court requires additional documentation, title company identifies unexpected liens or claims.",
  },
  {
    title: "Earnest Money Dispute Prevention SOP",
    description: "Protect earnest money deposits and avoid disputes before they happen. Covers Texas-specific contract language, documentation requirements, and escalation procedures that keep deals on track.",
    category: "Real Estate",
    format: "SOP Document",
    imageUrl: "/attached_assets/generated_images/earnest_money_dispute_sop.png",
    price: 12900,
    isFeatured: 1,
    assetType: "sop",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This SOP helps licensed Texas real estate agents prevent earnest money disputes through proper documentation, clear contract language, and established escalation procedures.",
    useConditions: "Use when: Accepting earnest money deposits, drafting contract terms, dispute arises over deposit release. Not applicable when: Cash transactions without earnest money, commercial transactions with different deposit structures.",
    risksAddressed: "Addresses: Earnest money release disputes, contract termination ambiguity, documentation gaps leading to TREC complaints, title company release delays.",
    coreContent: "Standard operating procedures for earnest money handling including deposit documentation, contract contingency language, termination procedures, and dispute resolution protocols.",
    failurePoints: "Common failure points: Unclear contract termination language, missing deposit receipt documentation, failure to follow proper release procedures.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Maintain copies of all deposit receipts, release authorizations, and dispute correspondence.",
    judgmentBoundary: "Requires agent judgment when: Both parties claim deposit entitlement, contract language is ambiguous, title company requires additional documentation for release.",
  },
  {
    title: "First-Time Landlord Mistake Prevention SOP",
    description: "Avoid the 15 most expensive mistakes new landlords make. Covers tenant screening, lease terms, security deposits, and maintenance protocols that protect your investment from day one.",
    category: "Landlord",
    format: "SOP Document",
    imageUrl: "/attached_assets/generated_images/first-time_landlord_sop.png",
    price: 12900,
    isFeatured: 1,
    assetType: "sop",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This SOP helps licensed Texas real estate agents advise first-time landlord clients on avoiding common costly mistakes in tenant screening, lease preparation, and property management.",
    useConditions: "Use when: Client converting primary residence to rental, investor purchasing first rental property, landlord experiencing tenant issues. Not applicable when: Commercial property leasing, property management company already engaged.",
    risksAddressed: "Addresses: Fair housing violations, improper security deposit handling, lease term deficiencies, maintenance liability exposure, eviction procedure errors.",
    coreContent: "15 critical mistake prevention protocols covering tenant screening compliance, lease clause requirements, security deposit procedures, maintenance documentation, and eviction preparation.",
    failurePoints: "Common failure points: Discriminatory screening practices, verbal agreements without documentation, security deposit commingling with personal funds.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Advise clients to maintain tenant files for 7 years after tenancy ends.",
    judgmentBoundary: "Requires agent judgment when: Tenant screening reveals borderline qualifications, lease terms need customization for specific situations, maintenance requests involve safety concerns.",
  },
  {
    title: "Heir Interference Prevention SOP",
    description: "Navigate family dynamics during estate property sales. Documented procedures for communication, decision-making authority, and conflict resolution that keep sales moving forward.",
    category: "Real Estate",
    format: "SOP Document",
    imageUrl: "/attached_assets/generated_images/heir_interference_prevention_sop.png",
    price: 12900,
    isFeatured: 1,
    assetType: "sop",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This SOP helps licensed Texas real estate agents manage heir relationships during estate property sales with clear communication protocols and conflict resolution procedures.",
    useConditions: "Use when: Multiple heirs have opinions on sale, family conflict affects transaction, executor faces heir resistance. Not applicable when: Single heir with clear authority, heirs in complete agreement, no estate involvement.",
    risksAddressed: "Addresses: Heir interference with showings, conflicting sale instructions, unauthorized property access, emotional decision-making affecting transaction, TREC complaints from dissatisfied heirs.",
    coreContent: "Heir management protocols including authority verification, communication boundaries, conflict escalation procedures, and documentation requirements for disputed situations.",
    failurePoints: "Common failure points: Taking instructions from non-authorized heirs, failing to document heir communications, allowing heir access without executor approval.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document all heir communications with dates, times, and content.",
    judgmentBoundary: "Requires agent judgment when: Heirs make conflicting requests, emotional situations escalate, executor authority is questioned by other heirs.",
  },
  {
    title: "Mortgage Loan Fallout Prevention Checklist",
    description: "Stop financing issues before they kill your deal. Pre-qualification verification, documentation requirements, and backup plan strategies that ensure closings happen on schedule.",
    category: "Real Estate",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/mortgage_fallout_prevention.png",
    price: 12900,
    isFeatured: 1,
    assetType: "checklist",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This checklist helps licensed Texas real estate agents identify and prevent financing failures before they derail transactions through systematic pre-qualification verification.",
    useConditions: "Use when: Buyer using conventional or government financing, pre-approval received, preparing for contract execution. Not applicable when: Cash purchase, seller financing, commercial transactions.",
    risksAddressed: "Addresses: Financing denial at underwriting, appraisal shortfalls, employment verification failures, credit changes during escrow, documentation delays.",
    coreContent: "12-point financing verification checklist covering pre-approval validation, employment stability confirmation, credit monitoring, appraisal preparation, and backup financing identification.",
    failurePoints: "Common failure points: Accepting pre-qualification as pre-approval, not monitoring buyer credit changes, failing to prepare for appraisal gaps.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Maintain copies of all lender communications and pre-approval letters.",
    judgmentBoundary: "Requires agent judgment when: Buyer pre-approval contains conditions, employment situation changes during escrow, appraisal comes in below contract price.",
  },
  {
    title: "Buyer Credit Readiness Pre-Screen SOP",
    description: "Screen buyer financing before investing time in showings. Credit score requirements, debt-to-income calculations, and pre-approval verification procedures that save weeks of wasted effort.",
    category: "Real Estate",
    format: "SOP Document",
    imageUrl: "/attached_assets/generated_images/buyer_credit_pre-screen_sop.png",
    price: 12900,
    isFeatured: 1,
    assetType: "sop",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This SOP helps licensed Texas real estate agents efficiently screen buyer financial readiness before investing significant time in property showings.",
    useConditions: "Use when: New buyer inquiry, buyer claims pre-approval, buyer wants to view multiple properties. Not applicable when: Buyer provides verified proof of funds, investor with established track record.",
    risksAddressed: "Addresses: Wasted showing time on unqualified buyers, financing failures late in transaction, buyer disappointment when unable to purchase.",
    coreContent: "Buyer screening protocol including credit requirement verification, DTI ratio assessment, pre-approval letter validation, and down payment verification procedures.",
    failurePoints: "Common failure points: Accepting verbal claims of qualification, not verifying pre-approval currency, failing to confirm down payment source.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document all buyer financial representations for file protection.",
    judgmentBoundary: "Requires agent judgment when: Buyer borderline on qualification metrics, pre-approval from unfamiliar lender, buyer financial situation is complex.",
  },
  {
    title: "Inspection Objection Negotiation Script",
    description: "Word-for-word scripts for handling inspection objections. Covers major vs minor repairs, credit vs repair negotiations, and deal-saving language that protects your commission.",
    category: "Real Estate",
    format: "Script Template",
    imageUrl: "/attached_assets/generated_images/inspection_negotiation_script.png",
    price: 12900,
    isFeatured: 0,
    assetType: "script",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This script helps licensed Texas real estate agents navigate inspection objection negotiations with proven language that keeps transactions together.",
    useConditions: "Use when: Inspection reveals issues requiring negotiation, buyer requests repairs or credits, seller resists inspection requests. Not applicable when: As-is contract with no inspection contingency, new construction with builder warranty.",
    risksAddressed: "Addresses: Transaction failure over inspection issues, unrealistic repair expectations, credit vs repair disagreements, emotional escalation during negotiations.",
    coreContent: "Word-for-word negotiation scripts covering major system issues, cosmetic concerns, credit calculations, repair timelines, and deal-preservation language.",
    failurePoints: "Common failure points: Emotional responses to inspection issues, unrealistic seller expectations, failure to prioritize critical vs cosmetic issues.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document all negotiation communications and final agreements.",
    judgmentBoundary: "Requires agent judgment when: Inspection reveals unexpected major issues, parties have emotional attachment to positions, repair vs credit decision impacts closing timeline.",
  },
  {
    title: "Appraisal Gap Strategy Guide",
    description: "Navigate low appraisals without losing deals. Price adjustment strategies, gap financing options, and negotiation tactics that keep transactions together when values fall short.",
    category: "Real Estate",
    format: "Strategy Guide",
    imageUrl: "/attached_assets/generated_images/appraisal_gap_strategy_guide.png",
    price: 12900,
    isFeatured: 0,
    assetType: "guide",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This guide helps licensed Texas real estate agents handle appraisal shortfalls with proven strategies that keep transactions together when values fall short.",
    useConditions: "Use when: Appraisal comes in below contract price, buyer financing requires appraised value support, seller resists price reduction. Not applicable when: Cash purchase with no appraisal contingency, appraisal meets or exceeds contract price.",
    risksAddressed: "Addresses: Transaction failure due to appraisal gaps, buyer inability to cover difference, seller refusal to reduce price, timeline extensions affecting closing.",
    coreContent: "Appraisal gap resolution strategies including price renegotiation frameworks, buyer gap coverage options, seller concession structures, and appraisal reconsideration procedures.",
    failurePoints: "Common failure points: Not preparing parties for potential gap, failing to explore all resolution options, letting emotions drive negotiations.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document appraisal value, gap amount, and resolution agreement.",
    judgmentBoundary: "Requires agent judgment when: Gap amount is negotiable, buyer has limited additional funds, market conditions support reconsideration request.",
  },
  {
    title: "Financing Fallout Response Playbook",
    description: "Rescue deals when financing falls through. Emergency lender contacts, backup financing strategies, and timeline extension procedures that save transactions at the last minute.",
    category: "Real Estate",
    format: "Playbook",
    imageUrl: "/attached_assets/generated_images/financing_fallout_playbook.png",
    price: 12900,
    isFeatured: 0,
    assetType: "playbook",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This playbook helps licensed Texas real estate agents respond quickly when financing falls through with emergency procedures that save transactions.",
    useConditions: "Use when: Lender denies loan, underwriting conditions cannot be met, financing deadline approaches without clear to close. Not applicable when: Cash transaction, financing already funded, buyer wants to terminate.",
    risksAddressed: "Addresses: Last-minute financing denial, underwriting condition failures, timeline violations, earnest money disputes from financing failure.",
    coreContent: "Emergency response procedures including backup lender contacts, timeline extension requests, alternative financing identification, and earnest money protection protocols.",
    failurePoints: "Common failure points: Not having backup lender relationships, delayed response to financing issues, failure to request timeline extensions promptly.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document all lender communications and timeline extension requests.",
    judgmentBoundary: "Requires agent judgment when: Backup lender viability is uncertain, timeline extension request may be denied, buyer commitment level is unclear.",
  },
  {
    title: "Divorce-Related Property Sale Playbook",
    description: "Manage high-emotion divorce property sales professionally. Communication protocols, neutral party procedures, and documentation requirements that protect all parties and your license.",
    category: "Real Estate",
    format: "Playbook",
    imageUrl: "/attached_assets/generated_images/divorce_property_sale_playbook.png",
    price: 12900,
    isFeatured: 0,
    assetType: "playbook",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This playbook helps licensed Texas real estate agents navigate divorce property sales with professional protocols that protect all parties and your license.",
    useConditions: "Use when: Property sale required by divorce decree, both spouses remain on title, emotional conflict affects transaction. Not applicable when: Property already transferred to one spouse, amicable separation with clear agreement.",
    risksAddressed: "Addresses: Conflicting spouse instructions, court order violations, unauthorized property access, emotional interference with showings, TREC complaints from either party.",
    coreContent: "Divorce sale protocols including court order verification, dual communication procedures, showing access management, offer presentation requirements, and neutral party documentation.",
    failurePoints: "Common failure points: Taking instructions from one spouse without other's knowledge, allowing unauthorized access, failing to verify court order requirements.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Maintain copies of court orders and document all communications with both parties.",
    judgmentBoundary: "Requires agent judgment when: Spouses give conflicting instructions, court order language is ambiguous, emotional situations escalate during showings or negotiations.",
  },
];

// Texas Real Estate Products - Tier 2: Operational Stress & Reputation Protection (10 products)
const texasRealEstateTier2: InsertProduct[] = [
  {
    title: "New Client Intake SOP (Buyer)",
    description: "Streamlined buyer onboarding that sets expectations from day one. Covers needs assessment, timeline setting, financing verification, and communication preferences that reduce future problems.",
    category: "Real Estate",
    format: "SOP Document",
    imageUrl: "/attached_assets/generated_images/new_client_intake_buyer_sop.png",
    price: 12900,
    isFeatured: 0,
    assetType: "sop",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This SOP helps licensed Texas real estate agents onboard buyer clients efficiently with proper documentation and clear expectation-setting from the first meeting.",
    useConditions: "Use when: New buyer client engagement, buyer agency agreement execution, first consultation meeting. Not applicable when: Existing client with established relationship, referral with prior agent documentation.",
    risksAddressed: "Addresses: Miscommunicated expectations, financing surprises, timeline misunderstandings, communication preference conflicts, incomplete client information.",
    coreContent: "Buyer intake procedures including needs assessment questionnaire, financing verification checklist, timeline setting framework, and communication preference documentation.",
    failurePoints: "Common failure points: Skipping financing verification, not documenting timeline expectations, assuming communication preferences.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Maintain signed buyer agency agreements and intake documentation.",
    judgmentBoundary: "Requires agent judgment when: Buyer needs are complex or evolving, financing situation is unusual, timeline flexibility is required.",
  },
  {
    title: "New Client Intake SOP (Seller)",
    description: "Professional seller onboarding that positions you as the expert. Covers property evaluation, pricing strategy, timeline expectations, and marketing plan presentation.",
    category: "Real Estate",
    format: "SOP Document",
    imageUrl: "/attached_assets/generated_images/new_client_intake_seller_sop.png",
    price: 12900,
    isFeatured: 0,
    assetType: "sop",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This SOP helps licensed Texas real estate agents onboard seller clients professionally with proper property evaluation and expectation-setting procedures.",
    useConditions: "Use when: New seller client engagement, listing agreement execution, pre-listing consultation. Not applicable when: Existing client relisting property, builder or developer client with different processes.",
    risksAddressed: "Addresses: Overpriced listings, unrealistic timeline expectations, inadequate property preparation, marketing plan misunderstandings, incomplete disclosure documentation.",
    coreContent: "Seller intake procedures including property evaluation checklist, CMA presentation framework, timeline expectation setting, and marketing plan discussion guide.",
    failurePoints: "Common failure points: Not addressing pricing reality, skipping property condition discussion, failing to set timeline expectations.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Maintain signed listing agreements and intake documentation.",
    judgmentBoundary: "Requires agent judgment when: Property condition affects value significantly, seller has emotional attachment to price, market conditions are changing rapidly.",
  },
  {
    title: "Client Expectation Alignment Script",
    description: "Set realistic expectations before problems arise. Word-for-word scripts for discussing market conditions, timelines, pricing, and what clients can expect throughout the transaction.",
    category: "Real Estate",
    format: "Script Template",
    imageUrl: "/attached_assets/generated_images/client_expectation_script.png",
    price: 12900,
    isFeatured: 0,
    assetType: "script",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This script helps licensed Texas real estate agents set realistic client expectations with proven language that prevents misunderstandings and complaints.",
    useConditions: "Use when: Initial client meeting, market conditions change, client expectations appear unrealistic. Not applicable when: Client already has realistic expectations, situation requires broker intervention.",
    risksAddressed: "Addresses: Unrealistic price expectations, timeline misunderstandings, market condition misconceptions, service level disagreements, TREC complaints from disappointed clients.",
    coreContent: "Word-for-word scripts for market condition discussions, pricing reality conversations, timeline expectation setting, and service level clarification.",
    failurePoints: "Common failure points: Avoiding difficult conversations, agreeing with unrealistic expectations, not documenting expectation-setting conversations.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document expectation-setting conversations in client files.",
    judgmentBoundary: "Requires agent judgment when: Client emotional state affects receptiveness, market data conflicts with client beliefs, relationship preservation is critical.",
  },
  {
    title: "Transaction Timeline Communication Template",
    description: "Keep clients informed without constant phone calls. Pre-written milestone updates, status reports, and proactive communication templates that build trust and reduce anxiety.",
    category: "Real Estate",
    format: "Template Pack",
    imageUrl: "/attached_assets/generated_images/transaction_timeline_template.png",
    price: 12900,
    isFeatured: 0,
    assetType: "template",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This template pack helps licensed Texas real estate agents maintain proactive client communication throughout transactions with pre-written milestone updates.",
    useConditions: "Use when: Transaction under contract, client requires regular updates, complex transaction with many milestones. Not applicable when: Client prefers minimal communication, transaction completing quickly.",
    risksAddressed: "Addresses: Client anxiety from lack of communication, missed milestone notifications, inconsistent update quality, time spent drafting routine communications.",
    coreContent: "Pre-written communication templates for contract execution, inspection scheduling, appraisal ordering, loan updates, and closing preparation milestones.",
    failurePoints: "Common failure points: Inconsistent communication frequency, missing critical milestone updates, generic communications lacking transaction specifics.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Save copies of all client communications in transaction files.",
    judgmentBoundary: "Requires agent judgment when: Milestone timing is unusual, transaction complications require customized communication, client communication preferences differ from standard approach.",
  },
  {
    title: "Seller Readiness Reality Check Checklist",
    description: "Identify tire-kickers vs serious sellers before investing time. Motivation assessment, timeline verification, and pricing reality checks that qualify listings worth taking.",
    category: "Real Estate",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/seller_readiness_checklist.png",
    price: 12900,
    isFeatured: 0,
    assetType: "checklist",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This checklist helps licensed Texas real estate agents quickly assess seller motivation and readiness before investing significant time in listing presentations.",
    useConditions: "Use when: Evaluating potential listing opportunity, seller motivation unclear, pricing expectations unknown. Not applicable when: Referred seller with known motivation, repeat client with established relationship.",
    risksAddressed: "Addresses: Wasted time on unmotivated sellers, overpriced listings that don't sell, seller regret leading to early terminations, tire-kicker identification failure.",
    coreContent: "Seller assessment checklist covering motivation indicators, timeline verification, pricing expectation alignment, and property condition readiness factors.",
    failurePoints: "Common failure points: Taking listings without motivation verification, ignoring pricing expectation red flags, not assessing property condition impact on sale.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document seller readiness assessment in listing file.",
    judgmentBoundary: "Requires agent judgment when: Seller motivation is mixed, property has unique challenges, market conditions affect typical readiness indicators.",
  },
  {
    title: "Tenant Screening Compliance Checklist (TX)",
    description: "Screen tenants legally and effectively under Texas law. Application requirements, background check procedures, and fair housing compliance that protect you from discrimination claims.",
    category: "Landlord",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/tenant_screening_compliance.png",
    price: 12900,
    isFeatured: 0,
    assetType: "checklist",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This checklist helps licensed Texas real estate agents advise landlord clients on legally compliant tenant screening procedures under Texas and federal fair housing laws.",
    useConditions: "Use when: Advising landlord on tenant selection, screening applications for client, establishing screening criteria. Not applicable when: Commercial tenant screening, property management company handling screening.",
    risksAddressed: "Addresses: Fair housing discrimination claims, inconsistent screening practices, inadequate background check procedures, application handling violations.",
    coreContent: "Tenant screening compliance checklist covering application requirements, consistent criteria application, background check procedures, and fair housing documentation.",
    failurePoints: "Common failure points: Inconsistent criteria application, verbal criteria not documented, discriminatory language in communications.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Advise clients to maintain screening documentation for 7 years.",
    judgmentBoundary: "Requires agent judgment when: Applicant has borderline qualifications, screening reveals concerns requiring verification, multiple qualified applicants require selection.",
  },
  {
    title: "Security Deposit Handling SOP",
    description: "Handle security deposits by the book under Texas Property Code. Collection, holding, documentation, and return procedures that prevent lawsuits and protect your reputation.",
    category: "Landlord",
    format: "SOP Document",
    imageUrl: "/attached_assets/generated_images/security_deposit_handling_sop.png",
    price: 12900,
    isFeatured: 0,
    assetType: "sop",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This SOP helps licensed Texas real estate agents advise landlord clients on proper security deposit handling under Texas Property Code requirements.",
    useConditions: "Use when: Advising landlord on deposit collection, tenant move-out processing, deposit dispute resolution. Not applicable when: Property management company handles deposits, commercial lease deposits.",
    risksAddressed: "Addresses: Improper deposit holding, return timeline violations, inadequate damage documentation, bad faith penalties, tenant lawsuits.",
    coreContent: "Security deposit procedures covering collection documentation, proper holding requirements, move-out inspection protocols, and return timeline compliance.",
    failurePoints: "Common failure points: Commingling deposits with personal funds, missing 30-day return deadline, inadequate damage documentation.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Advise clients to maintain deposit documentation for 7 years after tenancy ends.",
    judgmentBoundary: "Requires agent judgment when: Damage assessment is disputed, deposit amount disputed, tenant claims exceed normal wear and tear.",
  },
  {
    title: "Lease Violation Documentation Checklist",
    description: "Document violations properly for enforcement or eviction. Notice requirements, photo documentation standards, and timeline tracking that hold up in Texas courts.",
    category: "Landlord",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/lease_violation_checklist.png",
    price: 12900,
    isFeatured: 0,
    assetType: "checklist",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This checklist helps licensed Texas real estate agents advise landlord clients on proper lease violation documentation that holds up in Texas courts.",
    useConditions: "Use when: Tenant violates lease terms, landlord considering enforcement action, eviction preparation required. Not applicable when: Tenant in compliance, minor issues resolved informally.",
    risksAddressed: "Addresses: Inadequate violation documentation, improper notice procedures, evidence insufficiency in court, retaliation claim exposure.",
    coreContent: "Violation documentation checklist covering notice requirements, photo documentation standards, witness statements, timeline tracking, and court preparation.",
    failurePoints: "Common failure points: Verbal warnings without documentation, photos without timestamps, missing notice delivery confirmation.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Advise clients to maintain violation documentation indefinitely for legal protection.",
    judgmentBoundary: "Requires agent judgment when: Violation severity is borderline, tenant has extenuating circumstances, informal resolution may be preferable.",
  },
  {
    title: "Vacant Property Risk Mitigation Checklist",
    description: "Protect vacant properties from damage, liability, and insurance issues. Security measures, utility management, and inspection schedules that prevent costly surprises.",
    category: "Landlord",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/vacant_risk_mitigation.png",
    price: 12900,
    isFeatured: 0,
    assetType: "checklist",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This checklist helps licensed Texas real estate agents advise clients on protecting vacant properties from damage, liability, and insurance coverage gaps.",
    useConditions: "Use when: Property vacant between tenants, estate property awaiting sale, extended owner absence. Not applicable when: Property continuously occupied, short vacancy periods.",
    risksAddressed: "Addresses: Vandalism and theft exposure, water damage from undetected leaks, insurance coverage lapses, liability from property condition.",
    coreContent: "Vacant property protection checklist covering security measures, utility management, insurance notification, inspection schedules, and neighbor coordination.",
    failurePoints: "Common failure points: Not notifying insurance of vacancy, inadequate security measures, no regular inspection schedule.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document all inspection visits and security measures implemented.",
    judgmentBoundary: "Requires agent judgment when: Extended vacancy requires additional measures, property condition creates unusual risks, budget constraints limit protection options.",
  },
  {
    title: "Out-of-State Executor Coordination SOP",
    description: "Manage estate sales when the executor is remote. Communication protocols, local vendor coordination, and decision-making procedures that keep transactions moving despite distance.",
    category: "Real Estate",
    format: "SOP Document",
    imageUrl: "/attached_assets/generated_images/out-of-state_executor_sop.png",
    price: 12900,
    isFeatured: 0,
    assetType: "sop",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This SOP helps licensed Texas real estate agents manage estate property sales efficiently when the executor lives out of state and cannot be physically present.",
    useConditions: "Use when: Executor resides outside Texas, limited executor availability for property access, remote decision-making required. Not applicable when: Executor local and available, property manager handling coordination.",
    risksAddressed: "Addresses: Communication delays affecting timeline, property access coordination failures, decision-making bottlenecks, vendor coordination without executor presence.",
    coreContent: "Remote executor coordination procedures covering communication protocols, vendor management, property access systems, and decision-making authority documentation.",
    failurePoints: "Common failure points: Inadequate communication systems, exceeding decision-making authority, property access coordination failures.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document all executor communications and authorizations.",
    judgmentBoundary: "Requires agent judgment when: Executor responsiveness is delayed, property issues require immediate decisions, vendor recommendations need executor approval.",
  },
];

// Texas Real Estate Products - Tier 3: Quiet Upsells & Bundling Gold (10 products)
const texasRealEstateTier3: InsertProduct[] = [
  {
    title: "Multiple Offer Handling Checklist",
    description: "Manage multiple offers professionally and legally. Presentation procedures, seller consultation scripts, and documentation requirements that protect all parties.",
    category: "Real Estate",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/multiple_offer_handling_checklist.png",
    price: 12900,
    isFeatured: 0,
    assetType: "checklist",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This checklist helps licensed Texas real estate agents handle multiple offer situations professionally with proper procedures that protect all parties.",
    useConditions: "Use when: Multiple offers received simultaneously, seller considering counteroffers to multiple buyers, bidding situation develops. Not applicable when: Single offer received, seller already accepted offer.",
    risksAddressed: "Addresses: Unfair treatment of buyers, disclosure violations, seller confusion in multiple offer situations, TREC complaints from unsuccessful buyers.",
    coreContent: "Multiple offer handling checklist covering presentation procedures, seller consultation scripts, documentation requirements, and buyer communication protocols.",
    failurePoints: "Common failure points: Inconsistent offer presentation, inadequate seller consultation, poor buyer communication about process.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document all offers received and presentation timing.",
    judgmentBoundary: "Requires agent judgment when: Offers have different terms requiring comparison, seller wants to counter multiple offers, timing of offers creates procedural questions.",
  },
  {
    title: "Backup Offer Management SOP",
    description: "Keep backup offers engaged and ready to activate. Communication templates, timeline management, and activation procedures that save deals when primaries fall through.",
    category: "Real Estate",
    format: "SOP Document",
    imageUrl: "/attached_assets/generated_images/backup_offer_management_sop.png",
    price: 12900,
    isFeatured: 0,
    assetType: "sop",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This SOP helps licensed Texas real estate agents manage backup offers effectively with procedures that keep secondary buyers engaged and ready to activate.",
    useConditions: "Use when: Primary contract accepted with backup offer, primary contract at risk of failure, seller wants backup protection. Not applicable when: No backup offers exist, primary contract certain to close.",
    risksAddressed: "Addresses: Lost backup buyers due to poor communication, activation procedure errors, timeline confusion when primary fails.",
    coreContent: "Backup offer management procedures covering buyer communication templates, status update schedules, activation procedures, and timeline documentation.",
    failurePoints: "Common failure points: Losing backup buyer interest through neglect, improper activation procedures, timing errors in backup communication.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document all backup offer communications and status updates.",
    judgmentBoundary: "Requires agent judgment when: Primary contract status is uncertain, backup buyer patience is limited, activation timing is critical.",
  },
  {
    title: "Price Reduction Decision Framework",
    description: "Data-driven approach to price reductions that sellers accept. Market analysis presentation, timing recommendations, and conversation scripts that move stale listings.",
    category: "Real Estate",
    format: "Strategy Guide",
    imageUrl: "/attached_assets/generated_images/price_reduction_framework.png",
    price: 12900,
    isFeatured: 0,
    assetType: "guide",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This guide helps licensed Texas real estate agents present price reduction recommendations with data-driven frameworks that sellers accept and understand.",
    useConditions: "Use when: Listing not generating activity, market feedback indicates overpricing, days on market exceed comparable sales. Not applicable when: Listing generating appropriate activity, market conditions justify current pricing.",
    risksAddressed: "Addresses: Seller resistance to necessary reductions, overpriced listings damaging reputation, extended days on market, seller-agent relationship strain.",
    coreContent: "Price reduction framework covering market analysis presentation, timing recommendations, conversation scripts, and reduction amount calculations.",
    failurePoints: "Common failure points: Recommending reductions without supporting data, poor timing of conversations, inadequate preparation for seller objections.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document all pricing discussions and market analyses provided.",
    judgmentBoundary: "Requires agent judgment when: Market data is mixed, seller emotional attachment affects receptiveness, reduction amount determination is unclear.",
  },
  {
    title: "Days-on-Market Reset Playbook",
    description: "Strategic approaches to resetting DOM without looking desperate. Timing strategies, listing modifications, and marketing refresh techniques that attract fresh buyer attention.",
    category: "Real Estate",
    format: "Playbook",
    imageUrl: "/attached_assets/generated_images/days-on-market_reset_playbook.png",
    price: 12900,
    isFeatured: 0,
    assetType: "playbook",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This playbook helps licensed Texas real estate agents strategically reset days on market for stale listings with legitimate modifications that attract fresh buyer attention.",
    useConditions: "Use when: Extended DOM affecting buyer perception, significant listing improvements made, market conditions changed since original listing. Not applicable when: No legitimate changes to justify reset, manipulation without substance.",
    risksAddressed: "Addresses: DOM stigma affecting buyer interest, buyer agent concerns about property history, seller frustration with extended marketing time.",
    coreContent: "DOM reset strategies covering timing considerations, legitimate modification requirements, marketing refresh techniques, and buyer perception management.",
    failurePoints: "Common failure points: Resetting without legitimate changes, poor timing of reset, inadequate marketing refresh to support new listing.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document listing changes that justify reset.",
    judgmentBoundary: "Requires agent judgment when: Modifications are borderline for reset justification, timing optimization is unclear, seller expectations for reset results.",
  },
  {
    title: "Seller Emotional Expectation Management Script",
    description: "Navigate emotional sellers with professionalism. Scripts for pricing reality, showing feedback, and market condition discussions that maintain relationships while speaking truth.",
    category: "Real Estate",
    format: "Script Template",
    imageUrl: "/attached_assets/generated_images/seller_expectation_script.png",
    price: 12900,
    isFeatured: 0,
    assetType: "script",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This script helps licensed Texas real estate agents navigate emotionally challenging seller conversations with professional language that maintains relationships.",
    useConditions: "Use when: Seller has strong emotional attachment to property or price, difficult news must be delivered, relationship strain developing. Not applicable when: Seller rational and receptive, news is positive.",
    risksAddressed: "Addresses: Seller-agent relationship breakdown, unrealistic expectations persisting, emotional decisions affecting transaction, TREC complaints from frustrated sellers.",
    coreContent: "Word-for-word scripts for pricing reality discussions, showing feedback delivery, market condition explanations, and expectation adjustment conversations.",
    failurePoints: "Common failure points: Avoiding difficult conversations, agreeing with unrealistic expectations to preserve relationship, poor timing of difficult news.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document difficult conversations in client files.",
    judgmentBoundary: "Requires agent judgment when: Timing of difficult conversation is critical, relationship preservation vs truth-telling balance, emotional state of seller affects approach.",
  },
  {
    title: "Mortgage Denial Recovery Playbook",
    description: "Help buyers bounce back from denial and find alternative paths to ownership. Lender referrals, credit repair timelines, and alternative financing options.",
    category: "Real Estate",
    format: "Playbook",
    imageUrl: "/attached_assets/generated_images/mortgage_denial_recovery_playbook.png",
    price: 12900,
    isFeatured: 0,
    assetType: "playbook",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This playbook helps licensed Texas real estate agents guide buyers through mortgage denial recovery with alternative paths to homeownership.",
    useConditions: "Use when: Buyer loan denied, buyer wants to continue home search after denial, credit improvement needed. Not applicable when: Buyer decides to abandon home purchase, denial is permanent disqualification.",
    risksAddressed: "Addresses: Lost buyer clients after denial, buyer discouragement ending relationship, missed alternative financing opportunities.",
    coreContent: "Recovery procedures covering denial reason analysis, credit improvement strategies, alternative lender identification, and timeline expectations for future qualification.",
    failurePoints: "Common failure points: Abandoning buyer after denial, not exploring alternative options, unrealistic timeline promises for recovery.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document denial reasons and recovery plan discussed.",
    judgmentBoundary: "Requires agent judgment when: Denial reasons suggest unlikely recovery, buyer motivation level is uncertain, alternative financing viability is unclear.",
  },
  {
    title: "FSBO Rescue Agent Playbook",
    description: "Convert frustrated FSBO sellers into listings. Timing strategies, value proposition scripts, and objection handling that wins listings from failed DIY attempts.",
    category: "Real Estate",
    format: "Playbook",
    imageUrl: "/attached_assets/generated_images/fsbo_rescue_agent_playbook.png",
    price: 12900,
    isFeatured: 0,
    assetType: "playbook",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This playbook helps licensed Texas real estate agents convert frustrated FSBO sellers into listings with proven timing and value proposition strategies.",
    useConditions: "Use when: FSBO listing has been active without success, seller showing frustration signs, FSBO expired or about to expire. Not applicable when: FSBO seller committed to DIY, recent FSBO listing with no frustration indicators.",
    risksAddressed: "Addresses: Missed listing opportunities from FSBO failures, poor timing of conversion attempts, inadequate objection handling.",
    coreContent: "FSBO conversion strategies covering timing indicators, value proposition scripts, common objection responses, and listing presentation adaptations.",
    failurePoints: "Common failure points: Approaching too early before frustration, inadequate differentiation from other agents, not addressing commission objection effectively.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document FSBO interactions and conversion discussions.",
    judgmentBoundary: "Requires agent judgment when: FSBO frustration level assessment, timing of approach, pricing conversation if FSBO was overpriced.",
  },
  {
    title: "Investor Deal Kill-Criteria Checklist",
    description: "Quickly identify deals not worth pursuing. ROI calculations, risk assessments, and red flag identification that saves time on unprofitable opportunities.",
    category: "Real Estate",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/investor_kill-criteria_checklist.png",
    price: 12900,
    isFeatured: 0,
    assetType: "checklist",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This checklist helps licensed Texas real estate agents quickly evaluate investment property opportunities with criteria that identify deals not worth pursuing.",
    useConditions: "Use when: Evaluating investment properties for clients, investor client considering multiple opportunities, quick assessment needed. Not applicable when: Owner-occupied purchase, investor has different criteria preferences.",
    risksAddressed: "Addresses: Wasted time on unprofitable deals, investor client dissatisfaction from poor recommendations, missed red flags on problem properties.",
    coreContent: "Investment property evaluation checklist covering ROI calculations, risk assessment factors, red flag indicators, and deal comparison frameworks.",
    failurePoints: "Common failure points: Incomplete financial analysis, missing property condition red flags, not considering exit strategy viability.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document investment property evaluations and recommendations.",
    judgmentBoundary: "Requires agent judgment when: Deal is borderline on criteria, investor risk tolerance differs from standard, market conditions affect typical thresholds.",
  },
  {
    title: "Contractor Scope Control Checklist",
    description: "Prevent scope creep and budget overruns on renovation projects. Written scope requirements, change order procedures, and payment milestone structures.",
    category: "Real Estate",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/contractor_scope_control_checklist.png",
    price: 12900,
    isFeatured: 0,
    assetType: "checklist",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This checklist helps licensed Texas real estate agents advise investor clients on contractor management with scope control procedures that prevent budget overruns.",
    useConditions: "Use when: Client hiring contractors for renovation, investment property requiring repairs, flip project management. Not applicable when: Client using property management for renovations, minor repairs not requiring contractor.",
    risksAddressed: "Addresses: Scope creep increasing costs, contractor disputes, payment timing issues, incomplete work at project end.",
    coreContent: "Contractor management checklist covering written scope requirements, change order procedures, payment milestone structures, and completion verification.",
    failurePoints: "Common failure points: Verbal scope agreements, paying ahead of completed work, inadequate change order documentation.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Advise clients to maintain contractor agreements and change orders.",
    judgmentBoundary: "Requires agent judgment when: Scope changes are necessary for unforeseen issues, contractor disputes require intervention, payment disputes arise.",
  },
  {
    title: "Vacant Property Lockdown Checklist",
    description: "Secure vacant properties against theft, vandalism, and liability. Security measures, neighbor notification, and monitoring procedures for extended vacancies.",
    category: "Landlord",
    format: "Checklist",
    imageUrl: "/attached_assets/generated_images/vacant_property_lockdown.png",
    price: 12900,
    isFeatured: 0,
    assetType: "checklist",
    tier: "individual",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This checklist helps licensed Texas real estate agents advise clients on comprehensive vacant property security for extended vacancy periods.",
    useConditions: "Use when: Property will be vacant for extended period, estate property awaiting sale, property between tenants for extended time. Not applicable when: Short vacancy between tenants, property continuously monitored.",
    risksAddressed: "Addresses: Theft and vandalism, undetected damage from leaks or weather, liability from property condition, insurance coverage requirements.",
    coreContent: "Vacant property security checklist covering physical security measures, neighbor notification, monitoring schedules, and insurance compliance.",
    failurePoints: "Common failure points: Inadequate physical security, no monitoring schedule, failure to maintain insurance notification requirements.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Document security measures and monitoring visits.",
    judgmentBoundary: "Requires agent judgment when: Security measures need customization for property, monitoring frequency determination, neighbor coordination approach.",
  },
];

// Premium Bundle Products (9 bundles)
const bundleProducts: InsertProduct[] = [
  // Transaction Risk Control Kit
  {
    title: "Transaction Risk Control Kit - Solo",
    description: "Essential transaction protection for individual agents. Includes Earnest Money Dispute Prevention SOP, Financing Fallout Response Playbook, and Inspection Objection Negotiation Script. Use this before your broker has to get involved.",
    category: "Bundle",
    format: "Bundle Pack",
    imageUrl: "/attached_assets/generated_images/transaction_risk_control_kit_solo.png",
    price: 12900,
    isFeatured: 1,
    assetType: "sop",
    tier: "bundle",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This bundle helps licensed Texas real estate agents protect transactions with essential risk mitigation documents covering the most common transaction failure points.",
    useConditions: "Use when: Starting real estate career, handling first transactions independently, need core protection documents. Not applicable when: Already have comprehensive transaction systems, brokerage provides all documents.",
    risksAddressed: "Addresses: Earnest money disputes, financing failures, inspection negotiation failures, transaction timeline violations, common agent errors.",
    coreContent: "Three-document bundle covering earnest money protection, financing backup procedures, and inspection negotiation scripts for individual agent use.",
    failurePoints: "Common failure points: Using documents without understanding context, not customizing for specific situations, failing to follow procedures consistently.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Maintain copies of all completed checklists and communications.",
    judgmentBoundary: "Requires agent judgment when: Situations deviate from standard procedures, multiple documents apply to single situation, broker consultation needed.",
  },
  {
    title: "Transaction Risk Control Kit - Pro",
    description: "Complete transaction protection for power agents and team leads. Everything in Solo plus Appraisal Gap Strategy Guide, Client Expectation Alignment Script, Transaction Timeline Communication Template, and Buyer Credit Readiness Pre-Screen SOP. Includes editable client-facing PDFs.",
    category: "Bundle",
    format: "Bundle Pack",
    imageUrl: "/attached_assets/generated_images/transaction_risk_control_kit_pro.png",
    price: 21900,
    isFeatured: 0,
    assetType: "sop",
    tier: "bundle",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This bundle helps high-volume Texas real estate agents and team leads with comprehensive transaction protection including client-facing materials.",
    useConditions: "Use when: Managing high transaction volume, leading team requiring consistent procedures, need client-facing materials. Not applicable when: Low transaction volume, brokerage provides comprehensive systems.",
    risksAddressed: "Addresses: All Solo risks plus appraisal gaps, client expectation misalignment, communication failures, buyer qualification failures.",
    coreContent: "Seven-document bundle covering all Solo contents plus appraisal strategies, client scripts, communication templates, and buyer screening for team use.",
    failurePoints: "Common failure points: Not training team on consistent usage, failing to customize client-facing materials, inconsistent implementation across team.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Maintain team training records and procedure acknowledgments.",
    judgmentBoundary: "Requires agent judgment when: Team members face unusual situations, client materials need customization, procedures require adaptation for specific circumstances.",
  },
  {
    title: "Transaction Risk Control Kit - Office License",
    description: "Enterprise-grade transaction protection for brokerages. All Pro assets with white-label rights for internal use, broker compliance disclaimer pages, and office-wide SOP adoption guide. Annual license for unlimited agents.",
    category: "Bundle",
    format: "Office License",
    imageUrl: "/attached_assets/generated_images/transaction_risk_control_office_license.png",
    price: 69900,
    isFeatured: 0,
    assetType: "sop",
    tier: "bundle",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This bundle helps Texas brokerages implement standardized transaction protection across all agents with white-label materials and compliance documentation.",
    useConditions: "Use when: Implementing brokerage-wide procedures, standardizing agent training, need white-label materials for brand consistency. Not applicable when: Small team without brokerage structure.",
    risksAddressed: "Addresses: All Pro risks plus brokerage liability exposure, inconsistent agent practices, training gaps, compliance documentation requirements.",
    coreContent: "Complete Pro bundle plus white-label rights, broker compliance disclaimers, office adoption guide, and training implementation materials for unlimited agents.",
    failurePoints: "Common failure points: Incomplete rollout to all agents, failure to update training annually, not maintaining compliance documentation.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Maintain agent acknowledgment records and training completion documentation.",
    judgmentBoundary: "Requires agent judgment when: Broker override needed for specific situations, procedures require brokerage-level customization, compliance questions arise.",
  },
  // Landlord & Rental Liability Shield
  {
    title: "Landlord Liability Shield - Solo",
    description: "Essential protection for new landlords. Includes First-Time Landlord Mistake Prevention SOP, Tenant Screening Compliance Checklist, and Security Deposit Handling SOP. Avoid the expensive mistakes before they happen.",
    category: "Bundle",
    format: "Bundle Pack",
    imageUrl: "/attached_assets/generated_images/landlord_liability_shield_solo.png",
    price: 12900,
    isFeatured: 0,
    assetType: "sop",
    tier: "bundle",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This bundle helps licensed Texas real estate agents advise first-time landlord clients with essential liability protection covering the most costly mistakes.",
    useConditions: "Use when: Client becoming landlord for first time, advising on rental property management basics, client needs core landlord documents. Not applicable when: Client has property management company, commercial property leasing.",
    risksAddressed: "Addresses: Fair housing violations, security deposit mishandling, tenant screening errors, lease deficiencies, first-time landlord mistakes.",
    coreContent: "Three-document bundle covering common landlord mistakes, compliant tenant screening, and proper security deposit handling for new landlords.",
    failurePoints: "Common failure points: Client not following procedures consistently, incomplete documentation, verbal agreements instead of written.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Advise clients to maintain landlord files for 7 years after tenancy ends.",
    judgmentBoundary: "Requires agent judgment when: Client situation differs from standard scenarios, property type creates unique requirements, local ordinances affect procedures.",
  },
  {
    title: "Landlord Liability Shield - Pro",
    description: "Complete landlord protection system. Everything in Solo plus Lease Violation Documentation Checklist, Vacant Property Risk Mitigation Checklist, and Maintenance Request Response procedures. For serious property investors.",
    category: "Bundle",
    format: "Bundle Pack",
    imageUrl: "/attached_assets/generated_images/landlord_liability_shield_pro.png",
    price: 21900,
    isFeatured: 0,
    assetType: "sop",
    tier: "bundle",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This bundle helps licensed Texas real estate agents advise serious property investors with comprehensive landlord protection covering all major liability areas.",
    useConditions: "Use when: Client has multiple rental properties, client needs comprehensive landlord systems, investor building rental portfolio. Not applicable when: Client has property management company handling all operations.",
    risksAddressed: "Addresses: All Solo risks plus lease violation documentation, vacant property liability, maintenance response failures, eviction preparation gaps.",
    coreContent: "Six-document bundle covering all Solo contents plus violation documentation, vacant property protection, and maintenance protocols for serious investors.",
    failurePoints: "Common failure points: Not implementing all procedures consistently, failing to document violations properly, maintenance response delays.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Advise clients to maintain comprehensive landlord documentation indefinitely.",
    judgmentBoundary: "Requires agent judgment when: Violation severity assessment needed, vacant property requires customized protection, maintenance priorities must be determined.",
  },
  {
    title: "Landlord Liability Shield - Office License",
    description: "Property management firm protection package. All Pro assets with editable lease addendum language, property manager onboarding checklist, and annual compliance update templates. White-label for internal use.",
    category: "Bundle",
    format: "Office License",
    imageUrl: "/attached_assets/generated_images/landlord_liability_shield_office.png",
    price: 69900,
    isFeatured: 0,
    assetType: "sop",
    tier: "bundle",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This bundle helps Texas property management firms implement standardized landlord protection across all managed properties with white-label materials.",
    useConditions: "Use when: Property management firm standardizing procedures, multiple property managers requiring training, firm needs white-label client materials. Not applicable when: Individual agent advising single landlord.",
    risksAddressed: "Addresses: All Pro risks plus firm liability exposure, inconsistent manager practices, onboarding gaps, compliance update requirements.",
    coreContent: "Complete Pro bundle plus white-label rights, lease addendum language, manager onboarding checklist, and annual compliance update templates for unlimited use.",
    failurePoints: "Common failure points: Incomplete manager training, failure to update procedures annually, inconsistent implementation across properties.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Maintain manager training records and property file documentation.",
    judgmentBoundary: "Requires agent judgment when: Manager override needed, procedures require property-specific customization, compliance questions require legal consultation.",
  },
  // Estate & Court Sale Control Pack
  {
    title: "Estate Sale Control Pack - Solo",
    description: "Essential estate property sale toolkit. Includes Texas Executor Property Sale Checklist, Heir Interference Prevention SOP, and Out-of-State Executor Coordination SOP. Navigate probate sales with confidence.",
    category: "Bundle",
    format: "Bundle Pack",
    imageUrl: "/attached_assets/generated_images/estate_sale_control_pack_solo.png",
    price: 12900,
    isFeatured: 0,
    assetType: "checklist",
    tier: "bundle",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This bundle helps licensed Texas real estate agents navigate estate property sales with essential documents covering executor coordination and heir management.",
    useConditions: "Use when: Taking estate property listing, executor needs guidance, family dynamics affecting sale. Not applicable when: Standard residential sale without estate involvement, property already transferred to single owner.",
    risksAddressed: "Addresses: Probate procedure errors, heir interference with sales, remote executor coordination failures, timeline violations, documentation gaps.",
    coreContent: "Three-document bundle covering executor checklist, heir management procedures, and remote executor coordination for individual agent use.",
    failurePoints: "Common failure points: Not verifying executor authority, taking instructions from unauthorized heirs, inadequate documentation of heir communications.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Maintain copies of court documents and heir communications indefinitely.",
    judgmentBoundary: "Requires agent judgment when: Heir conflicts escalate, executor authority is questioned, court procedures require clarification.",
  },
  {
    title: "Estate Sale Control Pack - Pro",
    description: "Complete estate sale management system. Everything in Solo plus Divorce-Related Property Sale Playbook, Vacant Property Lockdown Checklist, and Financing Fallout Response Playbook. For agents specializing in estate sales.",
    category: "Bundle",
    format: "Bundle Pack",
    imageUrl: "/attached_assets/generated_images/estate_sale_control_pack_pro.png",
    price: 21900,
    isFeatured: 0,
    assetType: "checklist",
    tier: "bundle",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This bundle helps Texas real estate agents specializing in estate and court-ordered sales with comprehensive procedures for complex situations.",
    useConditions: "Use when: Specializing in estate sales, handling divorce property sales, managing complex court-involved transactions. Not applicable when: Occasional estate sale without specialization.",
    risksAddressed: "Addresses: All Solo risks plus divorce sale complications, vacant estate property risks, financing failures in estate transactions.",
    coreContent: "Six-document bundle covering all Solo contents plus divorce sale procedures, vacant property protection, and financing backup for estate specialists.",
    failurePoints: "Common failure points: Not adapting procedures for specific estate situations, inadequate vacant property monitoring, divorce party communication errors.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Maintain comprehensive estate transaction documentation indefinitely.",
    judgmentBoundary: "Requires agent judgment when: Court orders contain unusual provisions, parties have conflicting interests, property condition creates unique challenges.",
  },
  {
    title: "Estate Sale Control Pack - Office License",
    description: "Law firm and brokerage estate sale package. All Pro assets with court-facing compliance checklists, attorney collaboration SOP, and risk disclaimer templates. Trusted by attorneys and executors alike.",
    category: "Bundle",
    format: "Office License",
    imageUrl: "/attached_assets/generated_images/estate_sale_control_pack_office.png",
    price: 69900,
    isFeatured: 0,
    assetType: "checklist",
    tier: "bundle",
    priceSolo: 12900,
    pricePro: 21900,
    priceOffice: 69900,
    purposeScope: "This bundle helps Texas brokerages and law firms implement standardized estate sale procedures with court-compliant documentation and attorney collaboration protocols.",
    useConditions: "Use when: Brokerage specializing in estate sales, law firm partnering with real estate agents, firm needs court-compliant documentation. Not applicable when: Individual agent handling occasional estate sale.",
    risksAddressed: "Addresses: All Pro risks plus firm liability in estate transactions, court compliance failures, attorney collaboration gaps, disclaimer requirements.",
    coreContent: "Complete Pro bundle plus court-facing checklists, attorney collaboration SOP, risk disclaimer templates, and white-label rights for firm use.",
    failurePoints: "Common failure points: Incomplete court documentation, attorney communication gaps, failure to update procedures for court requirement changes.",
    recordkeepingGuidance: "Retain completed forms for 4+ years per TREC requirements. Maintain court filing copies and attorney communications indefinitely.",
    judgmentBoundary: "Requires agent judgment when: Court requirements differ from standard, attorney provides conflicting guidance, firm procedures require case-specific adaptation.",
  },
];

// Combine all products (30 individual + 9 bundles = 39 total)
const productsData: InsertProduct[] = [
  ...texasRealEstateTier1,
  ...texasRealEstateTier2,
  ...texasRealEstateTier3,
  ...bundleProducts,
];

async function seed() {
  console.log("Starting database seed...");
  
  let existingProducts = await storage.getAllProducts();
  
  if (existingProducts.length === 0) {
    for (const product of productsData) {
      await storage.createProduct(product);
    }
    console.log(`Successfully seeded ${productsData.length} products!`);
    existingProducts = await storage.getAllProducts();
  } else {
    console.log(`Database already has ${existingProducts.length} products.`);
  }

  // Check if funnels already exist
  const existingFunnels = await storage.getAllFunnels();
  if (existingFunnels.length > 0) {
    console.log(`Database already has ${existingFunnels.length} funnels. Skipping funnel seed.`);
    process.exit(0);
    return;
  }

  // Helper function to find products by title
  const findProduct = (titlePart: string) => existingProducts.find(p => p.title.includes(titlePart));

  // Texas Real Estate products for funnels
  const txRiskSolo = findProduct("Transaction Risk Control Kit - Solo");
  const txRiskPro = findProduct("Transaction Risk Control Kit - Pro");
  const landlordSolo = findProduct("Landlord Liability Shield - Solo");
  const landlordPro = findProduct("Landlord Liability Shield - Pro");
  const estateSolo = findProduct("Estate Sale Control Pack - Solo");
  const estatePro = findProduct("Estate Sale Control Pack - Pro");
  
  // Individual TX products for order bumps and funnels
  const earnestMoneySOP = findProduct("Earnest Money Dispute Prevention SOP");
  const financingFallout = findProduct("Financing Fallout Response Playbook");
  const firstTimeLandlord = findProduct("First-Time Landlord Mistake Prevention SOP");
  const tenantScreening = findProduct("Tenant Screening Compliance Checklist");
  const txExecutor = findProduct("Texas Executor Property Sale Checklist");
  const heirInterference = findProduct("Heir Interference Prevention SOP");
  const appraisalGap = findProduct("Appraisal Gap Strategy Guide");
  const inspectionScript = findProduct("Inspection Objection Negotiation Script");
  const buyerCreditSOP = findProduct("Buyer Credit Readiness Pre-Screen SOP");
  const leaseViolation = findProduct("Lease Violation Documentation Checklist");
  const mortgageFallout = findProduct("Mortgage Loan Fallout Prevention Checklist");

  // Create Transaction Risk Control Funnel
  if (txRiskSolo && txRiskPro && earnestMoneySOP) {
    const txRiskFunnel = await storage.createFunnel({
      name: "Transaction Risk Control Funnel",
      description: "Post-purchase funnel for Transaction Risk Control Kit Solo buyers. Upsells to Pro tier.",
      entryProductId: txRiskSolo.id,
      isActive: 1,
    });
    console.log(`Created funnel: ${txRiskFunnel.name}`);

    await storage.createFunnelStep({
      funnelId: txRiskFunnel.id,
      stepType: "upsell",
      offerProductId: txRiskPro.id,
      priority: 1,
      priceOverride: 12900,
      headline: "Upgrade to Pro: Get the Complete Transaction Protection System",
      subheadline: "The Solo kit handles basics. The Pro kit handles EVERYTHING. Add 4 more critical documents including Appraisal Gap Strategy and Buyer Credit Pre-Screen. Save $90 when you upgrade now.",
      ctaText: "Yes! Upgrade to Pro for Just $129",
      declineText: "No thanks, Solo is enough for me",
      timerSeconds: 900,
      isActive: 1,
    });

    await storage.createFunnelStep({
      funnelId: txRiskFunnel.id,
      stepType: "downsell",
      offerProductId: earnestMoneySOP.id,
      priority: 2,
      priceOverride: 4900,
      headline: "At Least Grab This Critical Document",
      subheadline: "The Earnest Money Dispute Prevention SOP alone has saved agents thousands in lost deposits. Get it now at 60% off the standard price.",
      ctaText: "Add the Earnest Money SOP for $49",
      declineText: "No thanks, I'll pass",
      timerSeconds: 600,
      isActive: 1,
    });
  }

  // Create Landlord Liability Shield Funnel
  if (landlordSolo && landlordPro && firstTimeLandlord && tenantScreening) {
    const landlordFunnel = await storage.createFunnel({
      name: "Landlord Liability Shield Funnel",
      description: "Post-purchase funnel for Landlord Liability Shield Solo buyers. Upsells to Pro tier.",
      entryProductId: landlordSolo.id,
      isActive: 1,
    });
    console.log(`Created funnel: ${landlordFunnel.name}`);

    await storage.createFunnelStep({
      funnelId: landlordFunnel.id,
      stepType: "upsell",
      offerProductId: landlordPro.id,
      priority: 1,
      priceOverride: 14900,
      headline: "Upgrade to Pro: Complete Landlord Protection System",
      subheadline: "Handle every landlord situation with confidence. Pro includes Lease Violation Documentation, Vacant Property Protection, and Maintenance Protocols. Save $70 today only.",
      ctaText: "Yes! Upgrade to Pro for Just $149",
      declineText: "No thanks, Solo is enough",
      timerSeconds: 900,
      isActive: 1,
    });

    await storage.createFunnelStep({
      funnelId: landlordFunnel.id,
      stepType: "downsell",
      offerProductId: tenantScreening.id,
      priority: 2,
      priceOverride: 4900,
      headline: "Don't Miss the Tenant Screening Compliance Checklist",
      subheadline: "This single document prevents fair housing violations and discrimination claims. Get it at 60% off while this offer lasts.",
      ctaText: "Add Tenant Screening Checklist for $49",
      declineText: "No thanks, I'll figure it out",
      timerSeconds: 600,
      isActive: 1,
    });
  }

  // Create Estate Sale Control Funnel
  if (estateSolo && estatePro && txExecutor && heirInterference) {
    const estateFunnel = await storage.createFunnel({
      name: "Estate Sale Control Funnel",
      description: "Post-purchase funnel for Estate Sale Control Pack Solo buyers. Upsells to Pro tier.",
      entryProductId: estateSolo.id,
      isActive: 1,
    });
    console.log(`Created funnel: ${estateFunnel.name}`);

    await storage.createFunnelStep({
      funnelId: estateFunnel.id,
      stepType: "upsell",
      offerProductId: estatePro.id,
      priority: 1,
      priceOverride: 14900,
      headline: "Upgrade to Pro: Handle Every Estate Sale Scenario",
      subheadline: "Estate sales get complicated fast. The Pro pack includes Divorce Property Sale Playbook, Vacant Property Lockdown, and Financing Fallout Response. Save $70 on this upgrade.",
      ctaText: "Yes! Upgrade to Pro for Just $149",
      declineText: "No thanks, Solo will work",
      timerSeconds: 900,
      isActive: 1,
    });

    await storage.createFunnelStep({
      funnelId: estateFunnel.id,
      stepType: "downsell",
      offerProductId: heirInterference.id,
      priority: 2,
      priceOverride: 4900,
      headline: "At Least Get the Heir Interference Prevention SOP",
      subheadline: "Family dynamics kill more estate sales than any other factor. This SOP keeps heirs in check and sales on track. Get it at 60% off.",
      ctaText: "Add Heir Interference SOP for $49",
      declineText: "No thanks, I'll skip it",
      timerSeconds: 600,
      isActive: 1,
    });
  }

  // Create Earnest Money Entry Funnel
  if (earnestMoneySOP && txRiskSolo && financingFallout) {
    const earnestMoneyFunnel = await storage.createFunnel({
      name: "Earnest Money Protection Funnel",
      description: "Entry funnel for Earnest Money SOP buyers with transaction kit upsell.",
      entryProductId: earnestMoneySOP.id,
      isActive: 1,
    });
    console.log(`Created funnel: ${earnestMoneyFunnel.name}`);

    await storage.createFunnelStep({
      funnelId: earnestMoneyFunnel.id,
      stepType: "upsell",
      offerProductId: txRiskSolo.id,
      priority: 1,
      priceOverride: 9900,
      headline: "Get the Complete Transaction Risk Control Kit",
      subheadline: "You're protecting earnest money. Smart. Now protect the ENTIRE transaction. Get our best-selling bundle at $30 off today only.",
      ctaText: "Yes! Add Transaction Risk Kit for $99",
      declineText: "No thanks, just the SOP",
      timerSeconds: 900,
      isActive: 1,
    });

    await storage.createFunnelStep({
      funnelId: earnestMoneyFunnel.id,
      stepType: "downsell",
      offerProductId: financingFallout.id,
      priority: 2,
      priceOverride: 4900,
      headline: "Add the Financing Fallout Response Playbook",
      subheadline: "Earnest money disputes often come from financing failures. This playbook helps you rescue deals before deposits are at risk. Just $49.",
      ctaText: "Add Financing Fallout Playbook for $49",
      declineText: "No thanks, I'm all set",
      timerSeconds: 600,
      isActive: 1,
    });
  }

  // Create Order Bumps for Texas Real Estate Products
  if (txExecutor && heirInterference) {
    await storage.createOrderBump({
      productId: txExecutor.id,
      bumpProductId: heirInterference.id,
      bumpPrice: 4900,
      headline: "Add: Heir Interference Prevention SOP",
      description: "Estate sales often involve family conflict. This SOP provides procedures for handling heir objections and keeping sales on track. Add it now for just $49.",
      isActive: 1,
    });
  }

  if (earnestMoneySOP && financingFallout) {
    await storage.createOrderBump({
      productId: earnestMoneySOP.id,
      bumpProductId: financingFallout.id,
      bumpPrice: 4900,
      headline: "Add: Financing Fallout Response Playbook",
      description: "Protect your deals when financing falls through. Emergency procedures and backup strategies that save transactions. Just $49 when you add now.",
      isActive: 1,
    });
  }

  if (firstTimeLandlord && tenantScreening) {
    await storage.createOrderBump({
      productId: firstTimeLandlord.id,
      bumpProductId: tenantScreening.id,
      bumpPrice: 4900,
      headline: "Add: Tenant Screening Compliance Checklist",
      description: "Screen tenants legally and effectively under Texas law. Avoid discrimination claims and find quality tenants. Only $49.",
      isActive: 1,
    });
  }

  if (appraisalGap && inspectionScript) {
    await storage.createOrderBump({
      productId: appraisalGap.id,
      bumpProductId: inspectionScript.id,
      bumpPrice: 4900,
      headline: "Add: Inspection Objection Negotiation Script",
      description: "Handle inspection objections with confidence. Word-for-word scripts for major repairs, credits, and deal-saving negotiations. Just $49.",
      isActive: 1,
    });
  }

  if (txRiskSolo && buyerCreditSOP) {
    await storage.createOrderBump({
      productId: txRiskSolo.id,
      bumpProductId: buyerCreditSOP.id,
      bumpPrice: 4900,
      headline: "Add: Buyer Credit Pre-Screen SOP",
      description: "Screen buyer financing before wasting time on unqualified buyers. Credit verification procedures that save weeks of effort. Just $49.",
      isActive: 1,
    });
  }

  if (landlordSolo && leaseViolation) {
    await storage.createOrderBump({
      productId: landlordSolo.id,
      bumpProductId: leaseViolation.id,
      bumpPrice: 4900,
      headline: "Add: Lease Violation Documentation",
      description: "Document violations properly for enforcement or eviction. Procedures that hold up in Texas courts. Only $49 when you add now.",
      isActive: 1,
    });
  }

  if (mortgageFallout && appraisalGap) {
    await storage.createOrderBump({
      productId: mortgageFallout.id,
      bumpProductId: appraisalGap.id,
      bumpPrice: 4900,
      headline: "Add: Appraisal Gap Strategy Guide",
      description: "Low appraisals kill deals. This guide provides strategies to bridge the gap and keep transactions together. Just $49.",
      isActive: 1,
    });
  }

  console.log("Funnel and order bump seeding complete!");

  process.exit(0);
}

seed().catch((error) => {
  console.error("Seed failed:", error);
  process.exit(1);
});
